### ISSUE TITLE
Problem with installation 

### ISSUE THREAD

**Issue by xd2183** [dashee87/jobbR#3]
I am trying to install this web wrapper for my project. However, when I tried to install it, there is always an error message in R says "Error in 'git2r_clone': Unable to authenticate with supplied credentials" Would you please help me with that issue? thanks

**Comment by dashee87** [comment]
Hmm, looks like you tried `devtools::install_git("https://gitlab.com/dashee87/jobbR.git")`, because I'm seeing the same error. The alternative installation method `devtools::install_github("dashee87/jobbR")` works for me, so give that a go. If that also gives you an error, then please post that too. Good luck!

David

**Comment by xd2183** [comment]
Thank you very much! the second code worked for me.

Xu

**Comment by dashee87** [comment]
Cool. I'll close this issue and probably remove the git installation from the README.
